name: ambanga_challenge
description: Ambanga Technologies Flutter technical assessment.
publish_to: none

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.5"

dependencies:
  equatable: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

dev_dependencies:
  bloc_test: ^10.0.0
  fake_async: ^1.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^11.0.0
